### PR TITLE
Update Windows binary to v0.7.7

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @1000ch for a quick review. **Do not squash the patches**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Modules run in strict mode by default.

**Comment by 1000ch** [comment]
Module Scripts enables strict mode by default as you say.
But this module is used not only as Module Scripts, isn't it?

**Comment by XhmikosR** [comment]
I should have said ES6 http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code

**Comment by 1000ch** [comment]
Strict mode is not enabled on Node.js CommonJS implementation including v10. Only enblaed on ES Modules implementation (`import`/`export` + `.mjs`) by default.

**Comment by XhmikosR** [comment]
I see, let me rebase.

**Comment by XhmikosR** [comment]
@sindresorhus can you confirm?

**Comment by sindresorhus** [comment]
Yes, `'use strict';` should be preserved.

**Comment by XhmikosR** [comment]
All right, done. I totally had the wrong impression here since I thought when there was an import/export statement V8 detected this as a module thus it run in strict mode.

**Comment by XhmikosR** [comment]
These are upstream releases (not build) so you should look there http://optipng.sourceforge.net/.

There is a VirtusTotal link in the commit too.

**Pull request merged**
