### PR TITLE
Add support for setting custom binary site

### PR DESCRIPTION
**Pull request by d0whc3r**
Based on @leo108 pr

### CODE REVIEW

**Comment by leo108** [comment]
I'm really worried if maintainers are still maintaining this repo.

**Comment by d0whc3r** [comment]
yes... last commit was 1 year ago...
@1000ch is this repo maintained?

**Comment by danimalweb** [comment]
Can this be merged?

**Comment by levin-du** [comment]
@1000ch We need this, thank you.

**Comment by sindresorhus** [comment]
https://github.com/imagemin/jpegtran-bin/pull/90#issuecomment-449864780

**Pull request closed without merging**
