### PR TITLE
Added FreeBSD/x64 binary

### LINKED ISSUE #64: FreeBSD x64 support
```
$ npm i optipng-bin
-
> optipng-bin@3.0.4 postinstall /usr/local/myproject/node_modules/optipng-bin
> node lib/install.js

ELF interpreter /libexec/ld-elf.so.1 not found
  ⚠ The `/usr/local/myproject/node_modules/optipng-bin/vendor/optipng` binary doesn't seem to work correctly
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/usr/local/myproject/node_modules/optipng-bin/vendor" --bindir="/usr/local/myproject/node_modules/optipng-bin/vendor" && make install
Command failed: /bin/sh -c make install
usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file ... target_directory

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
optipng-bin@3.0.4 node_modules/optipng-bin
├── logalot@2.1.0 (figures@1.4.0, squeak@1.3.0)
├── bin-wrapper@3.0.2 (os-filter-obj@1.0.3, lazy-req@1.1.0, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.4.3)
└── bin-build@2.2.0 (rimraf@2.5.0, exec-series@1.0.2, url-regex@3.1.0, archive-type@3.2.0, tempfile@1.1.1, decompress@3.0.0, download@4.4.3)
```

I'm guessing [this guy](https://github.com/imagemin/optipng-bin/blob/master/vendor/freebsd/optipng) is 32-bit?

I'll try to build you a 64-bit one if you're willing to accept a PR.

### PR DESCRIPTION
**Pull request by mnpenner**
Fixes #64

### CODE REVIEW

**Comment by sindresorhus** [comment]
You also need to update: https://github.com/imagemin/optipng-bin/blob/master/lib/index.js

**Comment by mnpenner** [comment]
Fixed.

**Comment by sindresorhus** [comment]
@shinnn Can you do a release? I have compilation problems and don't have time to look into it.

**Comment by shinnn** [comment]
Published 3.1.0.

**Pull request closed without merging**
